CREATE DATABASE IF NOT EXISTS eva_ai
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE eva_ai;

CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_conversations_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS memories (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    memory_type VARCHAR(50) NOT NULL DEFAULT 'episodic',
    content TEXT NOT NULL,
    importance DECIMAL(4,3) NOT NULL DEFAULT 0.500,
    emotional_value DECIMAL(4,3) NOT NULL DEFAULT 0.000,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_accessed DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS emotional_state (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    emotion VARCHAR(50) NOT NULL,
    intensity DECIMAL(4,3) NOT NULL DEFAULT 0.500,
    trust DECIMAL(4,3) NOT NULL DEFAULT 0.400,
    energy DECIMAL(4,3) NOT NULL DEFAULT 0.750,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
